name = "DataGeneratorTranslators"
uuid = "cb7b5811-d127-43cb-a6e6-05f80a66b803"
authors = ["Simon Poulding"]
version = "0.1.0"

[deps]
LightXML = "9c8b4983-aa76-5018-a973-4c85ecc9e179"
ParserCombinator = "fae87a5f-d1ad-5cf0-8f61-c941e1580b46"

[compat]
julia = "1.2"